# Generated by Django 5.1.6 on 2025-03-07 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articlecategory",
            options={"ordering": ["name"],
                     "verbose_name_plural": "Article Categories"},
        ),
    ]
