# Generated by Django 5.1.6 on 2025-03-07 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_alter_articlecategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['category__name', 'title']},
        ),
    ]
