# Generated by Django 5.1.6 on 2025-03-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_on']},
        ),
    ]
