# Generated by Django 5.1.6 on 2025-04-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0007_alter_article_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["category__name", "-created_on"]},
        ),
    ]
