# Generated by Django 5.1.6 on 2025-02-28 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("people_req", models.BigIntegerField()),
                ("date_created_on", models.DateTimeField(auto_now_add=True)),
                ("date_updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["date_created_on"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry", models.TextField()),
                ("date_created_on", models.DateTimeField(auto_now_add=True)),
                ("date_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "commission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="commission.commission",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created_on"],
            },
        ),
    ]
