# Generated by Django 5.2 on 2025-05-04 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "commission",
            "0003_remove_commission_people_required_commission_author_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="commission.job",
            ),
        ),
    ]
