# Generated by Django 5.2 on 2025-05-04 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commission", "0005_alter_jobapplication_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="commission.job"
            ),
        ),
    ]
