# Generated by Django 5.2 on 2025-05-08 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0001_initial"),
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="author_forum",
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comments",
                to="user_management.profile",
            ),
        ),
    ]
