# Generated by Django 5.2 on 2025-05-08 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0003_remove_comment_author_comment_author_forum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments_forums",
                to="forum.thread",
            ),
        ),
    ]
