# Generated by Django 5.1.6 on 2025-03-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0004_alter_postcategory_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
