# Generated by Django 5.2 on 2025-05-08 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0004_alter_comment_thread"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author_forum",
            new_name="author",
        ),
    ]
