# Generated by Django 5.1.6 on 2025-03-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_articlecategory_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
