# Generated by Django 5.1.6 on 2025-02-28 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchstore", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producttype",
            options={"ordering": ["name"],
                     "verbose_name_plural": "Product Types"},
        ),
    ]
