# Generated by Django 5.1.6 on 2025-02-28 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchstore", "0002_alter_producttype_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producttype",
            options={"ordering": ["name"],
                     "verbose_name_plural": "Product Type"},
        ),
    ]
