# Generated by Django 5.1.6 on 2025-05-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchstore", "0002_alter_transaction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("On cart", "On cart"),
                    ("To Pay", "To Pay"),
                    ("To Ship", "To Ship"),
                    ("To Receive", "To Receive"),
                    ("Delivered", "Delivered"),
                ],
                default="On cart",
                max_length=20,
            ),
        ),
    ]
