# Generated by Django 5.1.6 on 2025-04-30 09:45

import django.db.models.deletion
import merchstore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchstore", "0003_alter_producttype_options"),
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producttype",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                default=merchstore.models.get_default_profile,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_management.profile",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("On sale", "On sale"),
                    ("Out of stock", "Out of stock"),
                ],
                default="Available",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("On cart", "On cart"),
                            ("To Pay", "To Pay"),
                            ("To Ship", "To Ship"),
                            ("To Receive", "To Receive"),
                            ("Delivered", "Delivered"),
                        ],
                        default="On cart",
                        max_length=20,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user_management.profile",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="merchstore.product",
                    ),
                ),
            ],
        ),
    ]
